### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by omkarakatta** [omkarakatta/diftrans#27]
- [x] Evaluate empirical costs at all bandwidths, not just "acceptable" bandwidths
- [x] Add sections to code
- [x] Choose better names for output objects
- [x] Remove unnecessary arguments
- [x] Error checks
  - [x] check that `pre_main_subsample_size` and others is not NULL before checking it is an integer
  - ~choose defaults for subsample size? maybe not~
  - [x] ignore `*_control_subsample_size` if estimator is "ba"
- [x] Update documentation
- [x] Create `print` and `summary` methods
  - [x] `print` --- basic output
  - [x] `summary` --- full output
  - ~`summary_placebo` --- summarize placebo results~
  - ~`summary_subsample` --- summarize subsample results~
- [ ] Create `plot` and `table` methods
  - [x] `plot_data_hist` --- overlayed histograms of pre- and post-distributions
  - [ ] `plot_placebo_summary` --- plot summary results of placebo vs. bandwidth
  - [x] `plot_empirical` --- plot empirical results vs. bandwidth
    - [ ] add option for plotting placebo as well
    - [ ] add option for plotting treated and control, not just the difference
  - [x] `plot_placebo` --- plot placebo results vs. bandwidth (add option for plotting empirical as well)
  - [x] `plot_subsample` --- plot histogram of subsample results
- [ ] Create `retrieval` methods
  - [ ] `retrieve_placebo` --- send placebo results
  - [ ] `retrieve_subsample` --- send subsample results
  - [ ] `retrieve_empirical` --- send empirical results

**Comment by omkarakatta** [comment]
- [x] order `bandwidth_vec`; take unique values; ensure that it has non-zero length

**Comment by omkarakatta** [comment]
- [ ] Find a way to hide the vlines and hlines

**Comment by omkarakatta** [comment]
- [ ] Fix the default bandwidth selection criterion for difference-in-transports estimator (use d-d for bandwidth selection and use 2d-d for empirical computation and subsampling); allow option to use 2d-d for bandwidth selection criterion
- [ ] Go over subsampling procedure

**Comment by omkarakatta** [comment]
- [ ] Organize main and control distributions so they are in order according to the support
- [ ] Ensure that placebo is less than 0.05% (before-and-after)

**Comment by omkarakatta** [comment]
- [ ] Choose a random seed as default
